name: Sphinx & deploy - commit to gh-pages

on:
  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: sudo apt-get install pandoc

      - name: Install dependencies
        run: pip install -r doc_src/requirements.txt

      - name: Build
        working-directory: ${{github.workspace}}/doc_src
        run: |
          make html

      - name: Commit to gh-pages branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc_src/_build/html
